name: Build Windows & Mac Apps

on:
  push:
    branches:
    - main
  pull_request:
  
jobs:
  get_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@latest
        with:
          preset: "conventionalcommits"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-count: 0
          skip-on-empty: "false"
    
  build_windows:
      runs-on: windows-latest
      needs: get_version
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Use Version
        run: echo "Version is ${{ needs.get_version.outputs.version }}"
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Install Microsoft Visual C++ Redistributable
        run: choco install vcredist140 -y

  
      - name: Install dependencies
        run: |
          python -m venv venv
          venv/Scripts/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
  
      - name: Copy tk files into lib of venv
        run: |
          venv/Scripts/activate
          cp -r tk_files/* venv/lib/
  
      - name: Update App version for Windows PowerShell
        run: |
          (Get-Content powermeter_ui.py) -replace "v\.\d+\.\d+\.\d+", "" | Set-Content powermeter_ui.py
        shell: pwsh
  
      - name: Build App
        run: |
          venv/Scripts/activate
          pyinstaller --onefile --name "PowerMeterApp" --icon="ressources/QuebecWattAppLogo.ico" powermeter_ui.py
          
      - name: Create ZIP Archive on Windows
        run: |
          Compress-Archive dist/powermeter_ui.exe PowerMeterWindows${{ needs.get_version.outputs.version }}.zip
        shell: pwsh
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerMeterWindows${{ needs.get_version.outputs.version }}.zip
          path: PowerMeterWindows${{ needs.get_version.outputs.version }}.zip
        
  build_mac_and_release:
      runs-on: macos-latest
      needs: [build_windows, get_version]
  
      steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Use Version
        run: echo "Version is ${{ needs.get_version.outputs.version }}"
  
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          architecture: 'x64'
  
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install delocate py2app
          pip install -r requirements.txt
  
      - name: Copy tk files into lib of venv
        run: |
          source venv/bin/activate
          cp -r tk_files/* venv/lib/
  
      - name: Update App Version in powermeter_ui.py
        run: |
          sed -i "" "s/v\.[0-9]*\.[0-9]*\.[0-9]*/${{ needs.get_version.outputs.version }}/" powermeter_ui.py
  
      - name: Run ruff to format code
        run: |
          source venv/bin/activate
          ruff format
  
      - name: Commit and push changes
        run: |
          git pull
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if ! git diff-index --quiet HEAD --; then
              git commit -m "Apply ruff formatting"
              git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build App
        run: |
          source venv/bin/activate
          python setup.py py2app -v
  
      - name: Ensure execution permissions
        run: |
          chmod +x dist/*.app/Contents/MacOS/*
          ls -l dist/*.app/Contents/MacOS/
          
      - name: Zip App
        run: |
           cd dist/
           zip -r PowerMeterMac${{ needs.get_version.outputs.version }}.zip *.app
           
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: PowerMeterWindows${{ needs.get_version.outputs.version }}.zip
          path: .
           
      - name: GH Release
        uses: softprops/action-gh-release@v2
        if: ${{ needs.get_version.outputs.skipped == 'false' }}
        env:
          POWERMETER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
          tag_name: ${{ needs.get_version.outputs.version }}
          name: ${{ needs.get_version.outputs.version }}
          files: |
              dist/PowerMeterMac${{ needs.get_version.outputs.version }}.zip
              PowerMeterWindows${{ needs.get_version.outputs.version }}.zip
              CHANGELOG.md
              
